# Generated by Django 3.2.7 on 2021-09-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswdMgmtTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100)),
                ('ip_addr', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('who_changed', models.CharField(max_length=20)),
                ('root_passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'passwd_mgmt_table',
                'managed': False,
            },
        ),
    ]
