---

- name: install mariadb-server packages
  package:
    name: 
      - mariadb-server
      - python39-pip
      - python3-PyMySQL
    state: latest

- name: start mariadb server
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: install pymysql module using pip
  pip:
    name: pymysql
    executable: /usr/bin/pip3

- name: update mysql root password for root
  community.mysql.mysql_user:
    name: root 
    host:  localhost
    password: "{{db_root_pass}}"
    login_user: root
    #check if mysql allows login as root
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"

- name: update mysql root password for all accounts
  community.mysql.mysql_user:
    login_host: localhost
    login_user: root
    login_password: "{{db_root_pass}}"
    host:  "{{item}}"
    name: "{{db_user}}"
    password: "{{db_pass}}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create {{db_name}} database
  community.mysql.mysql_db:
    name: "{{db_name}}"
    state: present
    login_user: "{{db_user}}"
    login_password: "{{db_pass}}"

- name: Copy db-create-table.sql on target machine
  copy:
    src: db-create-table.sql
    dest: /tmp/
    owner: root
    group: root
    mode: 0644

- name: Create table {{db_table}}
  community.mysql.mysql_db:
    name: "{{db_name}}"
    state: import
    target: "/tmp/db-create-table.sql"
    login_user: "{{db_user}}"
    login_password: "{{db_pass}}"

- name: Remove copied file from host
  file:
    path: /tmp/db-create-table.sql
    state: absent